### ISSUE TITLE
windows下 运行flutter-pro-cli run check 报错

### ISSUE THREAD

**Issue by wang147** [love-flutter/flutter-pro-cli#2]
Start check file format
buffer.js:225
  throw new ERR_INVALID_ARG_TYPE(
  ^

TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type object
    at Function.from (buffer.js:225:9)
    at iconvDecode (D:\MyConfiguration\wangyu.wang\AppData\Roaming\npm\node_modules\flutter-pro-cli\lib\check_file.js:41:29)
    at exec (D:\MyConfiguration\wangyu.wang\AppData\Roaming\npm\node_modules\flutter-pro-cli\lib\check_file.js:19:33)
    at ChildProcess.exithandler (child_process.js:306:5)
    at ChildProcess.emit (events.js:193:13)
    at maybeClose (internal/child_process.js:999:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:266:5)

**Comment by love-flutter** [comment]
你更新一个版本试下，npm install flutter-pro-cli
